feat: add geo.point support
fuelen/ecto_dev_logger pull request #24
Opened 2023-08-26 15:24 UTC by iloveitaly

related to #22

2023-08-26 21:10 UTC, fuelen commented
Thank you for the PR.

Could you add `geo` as an optional dependency and a couple of tests?

2023-08-27 01:54 UTC, iloveitaly commented
done!

2023-08-27 11:43 UTC, fuelen requested changes

2023-08-27 11:43 UTC, fuelen commented on mix.exs
> +      {:geo, "~> 3.5.1", only: :test},
please make it `optional` and not only for `:test`

2023-08-27 11:43 UTC, fuelen commented on test/ecto/dev_logger/printable_parameter_test.exs
> +      "'{\"%Geo.Point{coordinates: {44.21587, -87.5947}, properties: %{}, srid: 4326}\"}'"
This is not a valid string representation of geo point.
I didn't use postgis, so I can't help here, but quick googling shows, that it should be represented like `SRID=4326;POINT(44.21587 -87.5947)`

2024-07-30 09:23 UTC, javiercr commented
Heads up! I open new PR to finish the work started here!

2024-07-30 20:57 UTC, closed without merging